use std::rc::Rc;

use super::RVInstructionNode;

/// This module contains a wrapper for the `ParserNode` enum that implements `PartialEq` and Eq
///
/// By default, equality is checked by comparing the id (generated by UUID) of two `ParserNodes`.
/// If we want to check if the data of two `ParserNodes` are equal, we can use this wrapper.
///
/// This is needed for testing as we want to check if the data of two `ParserNodes` are equal.
#[derive(Debug, Clone)]
pub struct ParserNodeDataWrapper(pub RVInstructionNode);

impl PartialEq for ParserNodeDataWrapper {
    fn eq(&self, other: &Self) -> bool {
        match (&self.0, &other.0) {
            (RVInstructionNode::Arith(a), RVInstructionNode::Arith(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.rs1 == b.rs1 && a.rs2 == b.rs2
            }
            (RVInstructionNode::IArith(a), RVInstructionNode::IArith(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.rs1 == b.rs1 && a.imm == b.imm
            }
            (RVInstructionNode::JumpLink(a), RVInstructionNode::JumpLink(b)) => {
                a.inst == b.inst && a.name == b.name
            }
            (RVInstructionNode::JumpLinkR(a), RVInstructionNode::JumpLinkR(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.rs1 == b.rs1 && a.imm == b.imm
            }
            (RVInstructionNode::Basic(a), RVInstructionNode::Basic(b)) => a.inst == b.inst,
            (RVInstructionNode::Branch(a), RVInstructionNode::Branch(b)) => {
                a.inst == b.inst && a.rs1 == b.rs1 && a.rs2 == b.rs2 && a.name == b.name
            }
            (RVInstructionNode::Store(a), RVInstructionNode::Store(b)) => {
                a.inst == b.inst && a.rs1 == b.rs1 && a.rs2 == b.rs2 && a.imm == b.imm
            }
            (RVInstructionNode::Load(a), RVInstructionNode::Load(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.rs1 == b.rs1 && a.imm == b.imm
            }
            (RVInstructionNode::Csr(a), RVInstructionNode::Csr(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.csr == b.csr && a.rs1 == b.rs1
            }
            (RVInstructionNode::LoadAddr(a), RVInstructionNode::LoadAddr(b)) => {
                a.inst == b.inst && a.rd == b.rd && a.name == b.name
            }
            _ => false,
        }
    }
}
impl Eq for ParserNodeDataWrapper {}

pub trait ParserNodeData {
    fn data(&self) -> ParserNodeDataWrapper;
}

pub trait VecParserNodeData {
    fn data(&self) -> Vec<ParserNodeDataWrapper>;
}

impl ParserNodeData for RVInstructionNode {
    fn data(&self) -> ParserNodeDataWrapper {
        ParserNodeDataWrapper(self.clone())
    }
}

impl VecParserNodeData for Vec<RVInstructionNode> {
    fn data(&self) -> Vec<ParserNodeDataWrapper> {
        self.iter().map(ParserNodeData::data).collect()
    }
}

impl VecParserNodeData for Vec<Rc<RVInstructionNode>> {
    fn data(&self) -> Vec<ParserNodeDataWrapper> {
        self.iter().map(|x| x.data()).collect()
    }
}
