use std::{fmt::Display, str::FromStr};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum BasicType {
    Ebreak,
    Ecall,
    Uret,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum ArithType {
    Add,
    Addw,
    And,
    Or,
    Sll,
    Sllw,
    Slt,
    Sltu,
    Sra,
    Sraw,
    Srl,
    Srlw,
    Sub,
    Xor,
    Mul,
    Mulh,
    Mulhsu,
    Mulhu,
    Div,
    Divu,
    Divw,
    Rem,
    Remu,
    Remw,
    Remuw,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum BranchType {
    Beq,
    Bge,
    Bgeu,
    Blt,
    Bltu,
    Bne,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum IArithType {
    Addi,
    Addiw,
    Andi,
    Ori,
    Slli,
    Slliw,
    Slti,
    Sltiu,
    Srai,
    Sraiw,
    Srli,
    Srliw,
    Xori,
    Auipc, // Same as this
    Lui,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum LoadType {
    Lb,
    Lbu,
    Lh,
    Lhu,
    Lw,
    Lwu,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum StoreType {
    Sb,
    Sh,
    Sw,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum CsrType {
    Csrrw,
    Csrrs,
    Csrrc,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum CsrIType {
    Csrrwi,
    Csrrsi,
    Csrrci,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum IgnoreType {
    Fence,
    Fencei,
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum JumpLinkType {
    Jal,
    Tail, // Tail is a "jump-and-link" for long jumps that overwrites x6 as a temp
}

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum JumpLinkRType {
    Jalr,
}

#[derive(Debug, Clone, PartialEq, Copy, Eq)]
pub enum RVInst {
    Ret,
    Ebreak,
    Ecall,
    Nop,
    Add,
    Addw,
    And,
    Or,
    Sll,
    Sllw,
    Slt,
    Sltu,
    Sra,
    Sraw,
    Srl,
    Srlw,
    Sub,
    Xor,
    Mul,
    Mulh,
    Mulhsu,
    Mulhu,
    Div,
    Divu,
    Divw,
    Rem,
    Remu,
    Remw,
    Remuw,
    Beq,
    Bge,
    Bgeu,
    Blt,
    Bltu,
    Bne,
    Addi,
    Addiw,
    Andi,
    Ori,
    Slli,
    Slliw,
    Slti,
    Sltiu,
    Srai,
    Sraiw,
    Srli,
    Srliw,
    Xori,
    Lui,
    Lb,
    Lbu,
    Lh,
    Lhu,
    Lw,
    Lwu,
    Sb,
    Sh,
    Sw,
    Csrrw,
    Csrrs,
    Csrrc,
    Csrrwi,
    Csrrsi,
    Csrrci,
    Fence,
    Fencei,
    Jal,
    Jalr,
    Tail,
    Auipc,
    Beqz,
    Bnez,
    J,
    Jr,
    La,
    Li,
    Mv,
    Neg,
    Not,
    Seqz,
    Snez,
    Sltz,
    Sgt,
    Sgtu,
    Sgtz,
    B,
    Bltz,
    Bgez,
    Call,
    Bgt,
    Ble,
    Bgtu,
    Bleu,
    Bgtz,
    Blez,
    Csrc,
    Csrr,
    Csrs,
    Csrw,
    Csrci,
    Csrsi,
    Csrwi,
    Uret,
}

impl RVInst {
    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub fn all() -> Vec<RVInst> {
        vec![
            RVInst::Ret,
            RVInst::Ebreak,
            RVInst::Ecall,
            RVInst::Nop,
            RVInst::Add,
            RVInst::Addw,
            RVInst::And,
            RVInst::Or,
            RVInst::Sll,
            RVInst::Sllw,
            RVInst::Slt,
            RVInst::Sltu,
            RVInst::Sra,
            RVInst::Sraw,
            RVInst::Srl,
            RVInst::Srlw,
            RVInst::Sub,
            RVInst::Xor,
            RVInst::Mul,
            RVInst::Mulh,
            RVInst::Mulhsu,
            RVInst::Mulhu,
            RVInst::Div,
            RVInst::Divu,
            RVInst::Divw,
            RVInst::Rem,
            RVInst::Remu,
            RVInst::Remw,
            RVInst::Remuw,
            RVInst::Beq,
            RVInst::Bge,
            RVInst::Bgeu,
            RVInst::Blt,
            RVInst::Bltu,
            RVInst::Bne,
            RVInst::Addi,
            RVInst::Addiw,
            RVInst::Andi,
            RVInst::Ori,
            RVInst::Slli,
            RVInst::Slliw,
            RVInst::Slti,
            RVInst::Sltiu,
            RVInst::Srai,
            RVInst::Sraiw,
            RVInst::Srli,
            RVInst::Srliw,
            RVInst::Xori,
            RVInst::Lui,
            RVInst::Lb,
            RVInst::Lbu,
            RVInst::Lh,
            RVInst::Lhu,
            RVInst::Lw,
            RVInst::Lwu,
            RVInst::Sb,
            RVInst::Sh,
            RVInst::Sw,
            RVInst::Csrrw,
            RVInst::Csrrs,
            RVInst::Csrrc,
            RVInst::Csrrwi,
            RVInst::Csrrsi,
            RVInst::Csrrci,
            RVInst::Fence,
            RVInst::Fencei,
            RVInst::Jal,
            RVInst::Jalr,
            RVInst::Auipc,
            RVInst::Beqz,
            RVInst::Bnez,
            RVInst::J,
            RVInst::Jr,
            RVInst::La,
            RVInst::Li,
            RVInst::Mv,
            RVInst::Neg,
            RVInst::Not,
            RVInst::Seqz,
            RVInst::Snez,
            RVInst::Sltz,
            RVInst::Sgtz,
            RVInst::Sgtu,
            RVInst::B,
            RVInst::Bltz,
            RVInst::Bgez,
            RVInst::Call,
            RVInst::Bgt,
            RVInst::Ble,
            RVInst::Bgtu,
            RVInst::Bleu,
            RVInst::Bgtz,
            RVInst::Blez,
            RVInst::Csrc,
            RVInst::Csrr,
            RVInst::Csrs,
            RVInst::Csrw,
            RVInst::Csrci,
            RVInst::Csrsi,
            RVInst::Csrwi,
            RVInst::Uret,
        ]
        .into_iter()
        .collect()
    }
}

impl Display for RVInst {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RVInst::Ret => write!(f, "ret"),
            RVInst::Ebreak => write!(f, "ebreak"),
            RVInst::Ecall => write!(f, "ecall"),
            RVInst::Nop => write!(f, "nop"),
            RVInst::Add => write!(f, "add"),
            RVInst::Addw => write!(f, "addw"),
            RVInst::And => write!(f, "and"),
            RVInst::Or => write!(f, "or"),
            RVInst::Sll => write!(f, "sll"),
            RVInst::Sllw => write!(f, "sllw"),
            RVInst::Slt => write!(f, "slt"),
            RVInst::Sltu => write!(f, "sltu"),
            RVInst::Sra => write!(f, "sra"),
            RVInst::Sraw => write!(f, "sraw"),
            RVInst::Srl => write!(f, "srl"),
            RVInst::Srlw => write!(f, "srlw"),
            RVInst::Sub => write!(f, "sub"),
            RVInst::Xor => write!(f, "xor"),
            RVInst::Mul => write!(f, "mul"),
            RVInst::Mulh => write!(f, "mulh"),
            RVInst::Mulhsu => write!(f, "mulhsu"),
            RVInst::Mulhu => write!(f, "mulhu"),
            RVInst::Div => write!(f, "div"),
            RVInst::Divu => write!(f, "divu"),
            RVInst::Divw => write!(f, "divw"),
            RVInst::Rem => write!(f, "rem"),
            RVInst::Remu => write!(f, "remu"),
            RVInst::Remw => write!(f, "remw"),
            RVInst::Remuw => write!(f, "remuw"),
            RVInst::Beq => write!(f, "beq"),
            RVInst::Bge => write!(f, "bge"),
            RVInst::Bgeu => write!(f, "bgeu"),
            RVInst::Blt => write!(f, "blt"),
            RVInst::Bltu => write!(f, "bltu"),
            RVInst::Bne => write!(f, "bne"),
            RVInst::Addi => write!(f, "addi"),
            RVInst::Addiw => write!(f, "addiw"),
            RVInst::Andi => write!(f, "andi"),
            RVInst::Ori => write!(f, "ori"),
            RVInst::Slli => write!(f, "slli"),
            RVInst::Slliw => write!(f, "slliw"),
            RVInst::Slti => write!(f, "slti"),
            RVInst::Sltiu => write!(f, "sltiu"),
            RVInst::Srai => write!(f, "srai"),
            RVInst::Sraiw => write!(f, "sraiw"),
            RVInst::Srli => write!(f, "srli"),
            RVInst::Srliw => write!(f, "srliw"),
            RVInst::Xori => write!(f, "xori"),
            RVInst::Lui => write!(f, "lui"),
            RVInst::Lb => write!(f, "lb"),
            RVInst::Lbu => write!(f, "lbu"),
            RVInst::Lh => write!(f, "lh"),
            RVInst::Lhu => write!(f, "lhu"),
            RVInst::Lw => write!(f, "lw"),
            RVInst::Lwu => write!(f, "lwu"),
            RVInst::Sb => write!(f, "sb"),
            RVInst::Sh => write!(f, "sh"),
            RVInst::Sw => write!(f, "sw"),
            RVInst::Csrrw => write!(f, "csrrw"),
            RVInst::Csrrs => write!(f, "csrrs"),
            RVInst::Csrrc => write!(f, "csrrc"),
            RVInst::Csrrwi => write!(f, "csrrwi"),
            RVInst::Csrrsi => write!(f, "csrrsi"),
            RVInst::Csrrci => write!(f, "csrrci"),
            RVInst::Fence => write!(f, "fence"),
            RVInst::Fencei => write!(f, "fencei"),
            RVInst::Jal => write!(f, "jal"),
            RVInst::Tail => write!(f, "tail"),
            RVInst::Jalr => write!(f, "jalr"),
            RVInst::Auipc => write!(f, "auipc"),
            RVInst::Beqz => write!(f, "beqz"),
            RVInst::Bnez => write!(f, "bnez"),
            RVInst::J => write!(f, "j"),
            RVInst::Jr => write!(f, "jr"),
            RVInst::La => write!(f, "la"),
            RVInst::Li => write!(f, "li"),
            RVInst::Mv => write!(f, "mv"),
            RVInst::Neg => write!(f, "neg"),
            RVInst::Not => write!(f, "not"),
            RVInst::Seqz => write!(f, "seqz"),
            RVInst::Snez => write!(f, "snez"),
            RVInst::Sltz => write!(f, "sltz"),
            RVInst::Sgt => write!(f, "sgt"),
            RVInst::Sgtz => write!(f, "sgtz"),
            RVInst::Sgtu => write!(f, "sgtu"),
            RVInst::Bgez => write!(f, "bgez"),
            RVInst::Bltz => write!(f, "bltz"),
            RVInst::B => write!(f, "b"),
            RVInst::Call => write!(f, "call"),
            RVInst::Bgt => write!(f, "bgt"),
            RVInst::Ble => write!(f, "ble"),
            RVInst::Bgtu => write!(f, "bgtu"),
            RVInst::Bleu => write!(f, "bleu"),
            RVInst::Bgtz => write!(f, "bgtz"),
            RVInst::Blez => write!(f, "blez"),
            RVInst::Csrc => write!(f, "csrc"),
            RVInst::Csrr => write!(f, "csrr"),
            RVInst::Csrs => write!(f, "csrs"),
            RVInst::Csrw => write!(f, "csrw"),
            RVInst::Csrci => write!(f, "csrci"),
            RVInst::Csrsi => write!(f, "csrsi"),
            RVInst::Csrwi => write!(f, "csrwi"),
            RVInst::Uret => write!(f, "uret"),
        }
    }
}

pub enum RVInstType {
    Arith(ArithType),
    IArith(IArithType),
    Basic(BasicType),
    JumpLink(JumpLinkType),
    JumpLinkR(JumpLinkRType),
    Load(LoadType),
    Store(StoreType),
    Csr(CsrType),
    CsrI(CsrIType),
    Ignore(IgnoreType),
    Branch(BranchType),
    Pseudo(PseudoType),
    UpperArith(IArithType),
}

#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub enum PseudoType {
    Beqz,
    Bnez,
    Bltz,
    Bgez,
    J,
    Jr,
    La,
    Li,
    Mv,
    Neg,
    Nop,
    Not,
    Ret,
    Seqz,
    Snez,
    Sgt,
    Sgtz,
    Sgtu,
    Sltz,
    B,
    Call,
    Bgt,
    Ble,
    Bgtu,
    Bleu,
    Bgtz,
    Blez,
    Csrc,
    Csrr,
    Csrs,
    Csrw,
    Csrci,
    Csrsi,
    Csrwi,
}

impl FromStr for RVInst {
    type Err = ();

    #[allow(clippy::too_many_lines)]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "ret" => Ok(RVInst::Ret),
            "ebreak" => Ok(RVInst::Ebreak),
            "ecall" => Ok(RVInst::Ecall),
            "nop" => Ok(RVInst::Nop),
            "add" => Ok(RVInst::Add),
            "addw" => Ok(RVInst::Addw),
            "and" => Ok(RVInst::And),
            "or" => Ok(RVInst::Or),
            "sll" => Ok(RVInst::Sll),
            "sllw" => Ok(RVInst::Sllw),
            "slt" => Ok(RVInst::Slt),
            "sltu" => Ok(RVInst::Sltu),
            "sra" => Ok(RVInst::Sra),
            "sraw" => Ok(RVInst::Sraw),
            "srl" => Ok(RVInst::Srl),
            "srlw" => Ok(RVInst::Srlw),
            "sub" => Ok(RVInst::Sub),
            "xor" => Ok(RVInst::Xor),
            "mul" => Ok(RVInst::Mul),
            "mulh" => Ok(RVInst::Mulh),
            "mulhsu" => Ok(RVInst::Mulhsu),
            "mulhu" => Ok(RVInst::Mulhu),
            "div" => Ok(RVInst::Div),
            "divu" => Ok(RVInst::Divu),
            "divw" => Ok(RVInst::Divw),
            "rem" => Ok(RVInst::Rem),
            "remu" => Ok(RVInst::Remu),
            "remw" => Ok(RVInst::Remw),
            "remuw" => Ok(RVInst::Remuw),
            "beq" => Ok(RVInst::Beq),
            "bge" => Ok(RVInst::Bge),
            "bgeu" => Ok(RVInst::Bgeu),
            "blt" => Ok(RVInst::Blt),
            "bltu" => Ok(RVInst::Bltu),
            "bne" => Ok(RVInst::Bne),
            "addi" => Ok(RVInst::Addi),
            "addiw" => Ok(RVInst::Addiw),
            "andi" => Ok(RVInst::Andi),
            "ori" => Ok(RVInst::Ori),
            "slli" => Ok(RVInst::Slli),
            "slliw" => Ok(RVInst::Slliw),
            "slti" => Ok(RVInst::Slti),
            "sltiu" => Ok(RVInst::Sltiu),
            "srai" => Ok(RVInst::Srai),
            "sraiw" => Ok(RVInst::Sraiw),
            "srli" => Ok(RVInst::Srli),
            "srliw" => Ok(RVInst::Srliw),
            "xori" => Ok(RVInst::Xori),
            "lui" => Ok(RVInst::Lui),
            "lb" => Ok(RVInst::Lb),
            "lbu" => Ok(RVInst::Lbu),
            "lh" => Ok(RVInst::Lh),
            "lhu" => Ok(RVInst::Lhu),
            "lw" => Ok(RVInst::Lw),
            "lwu" => Ok(RVInst::Lwu),
            "sb" => Ok(RVInst::Sb),
            "sh" => Ok(RVInst::Sh),
            "sw" => Ok(RVInst::Sw),
            "csrrw" => Ok(RVInst::Csrrw),
            "csrrs" => Ok(RVInst::Csrrs),
            "csrrc" => Ok(RVInst::Csrrc),
            "csrrwi" => Ok(RVInst::Csrrwi),
            "csrrsi" => Ok(RVInst::Csrrsi),
            "csrrci" => Ok(RVInst::Csrrci),
            "fence" => Ok(RVInst::Fence),
            "fencei" => Ok(RVInst::Fencei),
            "jal" => Ok(RVInst::Jal),
            "tail" => Ok(RVInst::Tail),
            "jalr" => Ok(RVInst::Jalr),
            "auipc" => Ok(RVInst::Auipc),
            "beqz" => Ok(RVInst::Beqz),
            "bnez" => Ok(RVInst::Bnez),
            "j" => Ok(RVInst::J),
            "jr" => Ok(RVInst::Jr),
            "la" => Ok(RVInst::La),
            "li" => Ok(RVInst::Li),
            "mv" => Ok(RVInst::Mv),
            "neg" => Ok(RVInst::Neg),
            "not" => Ok(RVInst::Not),
            "seqz" => Ok(RVInst::Seqz),
            "snez" => Ok(RVInst::Snez),
            "sgt" => Ok(RVInst::Sgt),
            "sgtz" => Ok(RVInst::Sgtz),
            "sgtu" => Ok(RVInst::Sgtu),
            "sltz" => Ok(RVInst::Sltz),
            "b" => Ok(RVInst::B),
            "bltz" => Ok(RVInst::Bltz),
            "bgez" => Ok(RVInst::Bgez),
            "call" => Ok(RVInst::Call),
            "bgt" => Ok(RVInst::Bgt),
            "ble" => Ok(RVInst::Ble),
            "bgtu" => Ok(RVInst::Bgtu),
            "bleu" => Ok(RVInst::Bleu),
            "bgtz" => Ok(RVInst::Bgtz),
            "blez" => Ok(RVInst::Blez),
            "csrc" => Ok(RVInst::Csrc),
            "csrr" => Ok(RVInst::Csrr),
            "csrs" => Ok(RVInst::Csrs),
            "csrw" => Ok(RVInst::Csrw),
            "csrci" => Ok(RVInst::Csrci),
            "csrsi" => Ok(RVInst::Csrsi),
            "csrwi" => Ok(RVInst::Csrwi),
            "uret" => Ok(RVInst::Uret),
            _ => Err(()),
        }
    }
}

impl From<&RVInst> for RVInstType {
    #[allow(clippy::too_many_lines)]
    fn from(value: &RVInst) -> Self {
        match value {
            RVInst::Add => RVInstType::Arith(ArithType::Add),
            RVInst::Addw => RVInstType::Arith(ArithType::Addw),
            RVInst::And => RVInstType::Arith(ArithType::And),
            RVInst::Or => RVInstType::Arith(ArithType::Or),
            RVInst::Sll => RVInstType::Arith(ArithType::Sll),
            RVInst::Sllw => RVInstType::Arith(ArithType::Sllw),
            RVInst::Slt => RVInstType::Arith(ArithType::Slt),
            RVInst::Sltu => RVInstType::Arith(ArithType::Sltu),
            RVInst::Sra => RVInstType::Arith(ArithType::Sra),
            RVInst::Sraw => RVInstType::Arith(ArithType::Sraw),
            RVInst::Srl => RVInstType::Arith(ArithType::Srl),
            RVInst::Srlw => RVInstType::Arith(ArithType::Srlw),
            RVInst::Sub => RVInstType::Arith(ArithType::Sub),
            RVInst::Xor => RVInstType::Arith(ArithType::Xor),
            RVInst::Mul => RVInstType::Arith(ArithType::Mul),
            RVInst::Mulh => RVInstType::Arith(ArithType::Mulh),
            RVInst::Mulhsu => RVInstType::Arith(ArithType::Mulhsu),
            RVInst::Mulhu => RVInstType::Arith(ArithType::Mulhu),
            RVInst::Div => RVInstType::Arith(ArithType::Div),
            RVInst::Divu => RVInstType::Arith(ArithType::Divu),
            RVInst::Divw => RVInstType::Arith(ArithType::Divw),
            RVInst::Rem => RVInstType::Arith(ArithType::Rem),
            RVInst::Remu => RVInstType::Arith(ArithType::Remu),
            RVInst::Remw => RVInstType::Arith(ArithType::Remw),
            RVInst::Remuw => RVInstType::Arith(ArithType::Remuw),
            RVInst::Beq => RVInstType::Branch(BranchType::Beq),
            RVInst::Bge => RVInstType::Branch(BranchType::Bge),
            RVInst::Bgeu => RVInstType::Branch(BranchType::Bgeu),
            RVInst::Blt => RVInstType::Branch(BranchType::Blt),
            RVInst::Bltu => RVInstType::Branch(BranchType::Bltu),
            RVInst::Bne => RVInstType::Branch(BranchType::Bne),
            RVInst::Addi => RVInstType::IArith(IArithType::Addi),
            RVInst::Addiw => RVInstType::IArith(IArithType::Addiw),
            RVInst::Andi => RVInstType::IArith(IArithType::Andi),
            RVInst::Ori => RVInstType::IArith(IArithType::Ori),
            RVInst::Slli => RVInstType::IArith(IArithType::Slli),
            RVInst::Slliw => RVInstType::IArith(IArithType::Slliw),
            RVInst::Slti => RVInstType::IArith(IArithType::Slti),
            RVInst::Sltiu => RVInstType::IArith(IArithType::Sltiu),
            RVInst::Srai => RVInstType::IArith(IArithType::Srai),
            RVInst::Sraiw => RVInstType::IArith(IArithType::Sraiw),
            RVInst::Srli => RVInstType::IArith(IArithType::Srli),
            RVInst::Srliw => RVInstType::IArith(IArithType::Srliw),
            RVInst::Xori => RVInstType::IArith(IArithType::Xori),
            RVInst::Lui => RVInstType::UpperArith(IArithType::Lui),
            RVInst::Lb => RVInstType::Load(LoadType::Lb),
            RVInst::Lbu => RVInstType::Load(LoadType::Lbu),
            RVInst::Lh => RVInstType::Load(LoadType::Lh),
            RVInst::Lhu => RVInstType::Load(LoadType::Lhu),
            RVInst::Lw => RVInstType::Load(LoadType::Lw),
            RVInst::Lwu => RVInstType::Load(LoadType::Lwu),
            RVInst::Sb => RVInstType::Store(StoreType::Sb),
            RVInst::Sh => RVInstType::Store(StoreType::Sh),
            RVInst::Sw => RVInstType::Store(StoreType::Sw),
            RVInst::Fence => RVInstType::Ignore(IgnoreType::Fence),
            RVInst::Fencei => RVInstType::Ignore(IgnoreType::Fencei),
            RVInst::Jal => RVInstType::JumpLink(JumpLinkType::Jal),
            RVInst::Tail => RVInstType::JumpLink(JumpLinkType::Tail),
            RVInst::Jalr => RVInstType::JumpLinkR(JumpLinkRType::Jalr),
            RVInst::Ecall => RVInstType::Basic(BasicType::Ecall),
            RVInst::Ebreak => RVInstType::Basic(BasicType::Ebreak),
            RVInst::Ret => RVInstType::Pseudo(PseudoType::Ret),
            RVInst::Csrrw => RVInstType::Csr(CsrType::Csrrw),
            RVInst::Csrrs => RVInstType::Csr(CsrType::Csrrs),
            RVInst::Csrrc => RVInstType::Csr(CsrType::Csrrc),
            RVInst::Csrrwi => RVInstType::CsrI(CsrIType::Csrrwi),
            RVInst::Csrrsi => RVInstType::CsrI(CsrIType::Csrrsi),
            RVInst::Csrrci => RVInstType::CsrI(CsrIType::Csrrci),
            RVInst::Nop => RVInstType::Pseudo(PseudoType::Nop),
            RVInst::Auipc => RVInstType::IArith(IArithType::Auipc),
            RVInst::Beqz => RVInstType::Pseudo(PseudoType::Beqz),
            RVInst::Bnez => RVInstType::Pseudo(PseudoType::Bnez),
            RVInst::J => RVInstType::Pseudo(PseudoType::J),
            RVInst::Jr => RVInstType::Pseudo(PseudoType::Jr),
            RVInst::Li => RVInstType::Pseudo(PseudoType::Li),
            RVInst::La => RVInstType::Pseudo(PseudoType::La),
            RVInst::Mv => RVInstType::Pseudo(PseudoType::Mv),
            RVInst::Neg => RVInstType::Pseudo(PseudoType::Neg),
            RVInst::Not => RVInstType::Pseudo(PseudoType::Not),
            RVInst::Seqz => RVInstType::Pseudo(PseudoType::Seqz),
            RVInst::Snez => RVInstType::Pseudo(PseudoType::Snez),
            RVInst::Sltz => RVInstType::Pseudo(PseudoType::Sltz),
            RVInst::Sgt => RVInstType::Pseudo(PseudoType::Sgt),
            RVInst::Sgtz => RVInstType::Pseudo(PseudoType::Sgtz),
            RVInst::Sgtu => RVInstType::Pseudo(PseudoType::Sgtu),
            RVInst::B => RVInstType::Pseudo(PseudoType::B),
            RVInst::Bltz => RVInstType::Pseudo(PseudoType::Bltz),
            RVInst::Bgez => RVInstType::Pseudo(PseudoType::Bgez),
            RVInst::Bgtz => RVInstType::Pseudo(PseudoType::Bgtz),
            RVInst::Blez => RVInstType::Pseudo(PseudoType::Blez),
            RVInst::Call => RVInstType::Pseudo(PseudoType::Call),
            RVInst::Bgt => RVInstType::Pseudo(PseudoType::Bgt),
            RVInst::Ble => RVInstType::Pseudo(PseudoType::Ble),
            RVInst::Bgtu => RVInstType::Pseudo(PseudoType::Bgtu),
            RVInst::Bleu => RVInstType::Pseudo(PseudoType::Bleu),
            RVInst::Csrc => RVInstType::Pseudo(PseudoType::Csrc),
            RVInst::Csrr => RVInstType::Pseudo(PseudoType::Csrr),
            RVInst::Csrs => RVInstType::Pseudo(PseudoType::Csrs),
            RVInst::Csrw => RVInstType::Pseudo(PseudoType::Csrw),
            RVInst::Csrci => RVInstType::Pseudo(PseudoType::Csrci),
            RVInst::Csrsi => RVInstType::Pseudo(PseudoType::Csrsi),
            RVInst::Csrwi => RVInstType::Pseudo(PseudoType::Csrwi),
            RVInst::Uret => RVInstType::Basic(BasicType::Uret),
        }
    }
}

impl From<&ArithType> for RVInst {
    fn from(value: &ArithType) -> Self {
        match value {
            ArithType::Add => RVInst::Add,
            ArithType::Addw => RVInst::Addw,
            ArithType::Sub => RVInst::Sub,
            ArithType::Mul => RVInst::Mul,
            ArithType::Div => RVInst::Div,
            ArithType::Divu => RVInst::Divu,
            ArithType::Divw => RVInst::Divw,
            ArithType::Rem => RVInst::Rem,
            ArithType::Remu => RVInst::Remu,
            ArithType::Remw => RVInst::Remw,
            ArithType::Remuw => RVInst::Remuw,
            ArithType::And => RVInst::And,
            ArithType::Or => RVInst::Or,
            ArithType::Xor => RVInst::Xor,
            ArithType::Sll => RVInst::Sll,
            ArithType::Sllw => RVInst::Sllw,
            ArithType::Slt => RVInst::Slt,
            ArithType::Sltu => RVInst::Sltu,
            ArithType::Sra => RVInst::Sra,
            ArithType::Sraw => RVInst::Sraw,
            ArithType::Srl => RVInst::Srl,
            ArithType::Srlw => RVInst::Srlw,
            ArithType::Mulh => RVInst::Mulh,
            ArithType::Mulhsu => RVInst::Mulhsu,
            ArithType::Mulhu => RVInst::Mulhu,
        }
    }
}

impl From<&IArithType> for RVInst {
    fn from(value: &IArithType) -> Self {
        match value {
            IArithType::Addi => RVInst::Addi,
            IArithType::Addiw => RVInst::Addiw,
            IArithType::Slliw => RVInst::Slliw,
            IArithType::Srliw => RVInst::Srliw,
            IArithType::Sraiw => RVInst::Sraiw,
            IArithType::Slti => RVInst::Slti,
            IArithType::Sltiu => RVInst::Sltiu,
            IArithType::Xori => RVInst::Xori,
            IArithType::Ori => RVInst::Ori,
            IArithType::Andi => RVInst::Andi,
            IArithType::Slli => RVInst::Slli,
            IArithType::Srli => RVInst::Srli,
            IArithType::Srai => RVInst::Srai,
            IArithType::Auipc => RVInst::Auipc,
            IArithType::Lui => RVInst::Lui,
        }
    }
}

impl From<&LoadType> for RVInst {
    fn from(value: &LoadType) -> Self {
        match value {
            LoadType::Lb => RVInst::Lb,
            LoadType::Lbu => RVInst::Lbu,
            LoadType::Lh => RVInst::Lh,
            LoadType::Lhu => RVInst::Lhu,
            LoadType::Lw => RVInst::Lw,
            LoadType::Lwu => RVInst::Lwu,
        }
    }
}

impl From<&StoreType> for RVInst {
    fn from(value: &StoreType) -> Self {
        match value {
            StoreType::Sb => RVInst::Sb,
            StoreType::Sh => RVInst::Sh,
            StoreType::Sw => RVInst::Sw,
        }
    }
}

impl From<&JumpLinkType> for RVInst {
    fn from(value: &JumpLinkType) -> Self {
        match value {
            JumpLinkType::Jal => RVInst::Jal,
            JumpLinkType::Tail => RVInst::Tail,
        }
    }
}

impl From<&JumpLinkRType> for RVInst {
    fn from(value: &JumpLinkRType) -> Self {
        match value {
            JumpLinkRType::Jalr => RVInst::Jalr,
        }
    }
}

impl From<&CsrType> for RVInst {
    fn from(value: &CsrType) -> Self {
        match value {
            CsrType::Csrrw => RVInst::Csrrw,
            CsrType::Csrrs => RVInst::Csrrs,
            CsrType::Csrrc => RVInst::Csrrc,
        }
    }
}

impl From<&CsrIType> for RVInst {
    fn from(value: &CsrIType) -> Self {
        match value {
            CsrIType::Csrrwi => RVInst::Csrrwi,
            CsrIType::Csrrsi => RVInst::Csrrsi,
            CsrIType::Csrrci => RVInst::Csrrci,
        }
    }
}

impl From<&BasicType> for RVInst {
    fn from(value: &BasicType) -> Self {
        match value {
            BasicType::Ecall => RVInst::Ecall,
            BasicType::Ebreak => RVInst::Ebreak,
            BasicType::Uret => RVInst::Uret,
        }
    }
}

impl From<&BranchType> for RVInst {
    fn from(value: &BranchType) -> Self {
        match value {
            BranchType::Beq => RVInst::Beq,
            BranchType::Bne => RVInst::Bne,
            BranchType::Blt => RVInst::Blt,
            BranchType::Bge => RVInst::Bge,
            BranchType::Bltu => RVInst::Bltu,
            BranchType::Bgeu => RVInst::Bgeu,
        }
    }
}
